FROM ruby:2.7.0

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev curl

ENV APP_PATH /usr/src/app

RUN mkdir -p $APP_PATH

COPY Gemfile $APP_PATH

COPY Gemfile.lock $APP_PATH

WORKDIR $APP_PATH

RUN bundle install

RUN gem install rails bundler

ADD . $APP_PATH

CMD ["rails", "server", "-b", "0.0.0.0"]
